__all__ = ['DEF_CONTEXT',
		   'MIN_RANDOMNESS', 'DEF_RANDOMNESS', 'MAX_RANDOMNESS',
		   'MIN_WORD_VARIETY', 'DEF_WORD_VARIETY', 'MAX_WORD_VARIETY',
		   'MIN_REPETITIVENESS', 'DEF_REPETITIVENESS', 'MAX_REPETITIVENESS',
		   'DEF_MAX_OUTPUT_TOKENS']

DEF_CONTEXT = ('You are a helpful assistant. Do not generate harmful, explicit, or biased content.')
MAX_RANDOMNESS = 2
DEF_RANDOMNESS = 1
MIN_RANDOMNESS = 0
MIN_WORD_VARIETY = 0
DEF_WORD_VARIETY = 0.5
MAX_WORD_VARIETY = 1
MIN_REPETITIVENESS = -2
DEF_REPETITIVENESS = 0
MAX_REPETITIVENESS = 2
DEF_MAX_OUTPUT_TOKENS = 4096
