name: Build and Push Docker Images

on:
  push:
    branches:
      - master  # or your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use GitHub token here for authentication
          registry: ghcr.io

      - name: Build and push frontend Docker image
        run: |
          docker build --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
                      --label "org.opencontainers.image.description=Frontend container for LLM Spot" \
                      -t ghcr.io/filipmojto/frontend:latest ./frontend
          docker push ghcr.io/filipmojto/frontend:latest

      - name: Build and push backend Docker image
        run: |
          docker build --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
                       --label "org.opencontainers.image.description=Backend container for LLM Spot" \
                       -t ghcr.io/filipmojto/backend:latest ./backend
          docker push ghcr.io/filipmojto/backend:latest